# Generated by Django 3.1.4 on 2020-12-10 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('junkfood', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menus',
            fields=[
                ('menu_id', models.AutoField(primary_key=True, serialize=False)),
                ('meny_img', models.ImageField(upload_to='')),
                ('menu_name', models.CharField(max_length=250)),
                ('menu_body', models.TextField()),
            ],
        ),
    ]
