# Generated by Django 3.1.4 on 2020-12-10 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('junkfood', '0002_menus'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profiles',
            fields=[
                ('profile_id', models.AutoField(primary_key=True, serialize=False)),
                ('profile_firstname', models.CharField(max_length=250)),
                ('profile_lasttname', models.CharField(max_length=250)),
                ('profile_pseudo', models.CharField(max_length=250)),
                ('profile_password', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Supplements',
            fields=[
                ('supplement_id', models.AutoField(primary_key=True, serialize=False)),
                ('supplement_name', models.CharField(max_length=250)),
            ],
        ),
    ]
